
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 27 12:07:09 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACECURLY = 7;
  public static final int INCREMENT = 46;
  public static final int CONST = 9;
  public static final int LOWER = 48;
  public static final int NOTEQUAL = 12;
  public static final int CONTINUE = 41;
  public static final int LPAREN = 22;
  public static final int GREATER = 13;
  public static final int LOWEREQUAL = 49;
  public static final int DECREMENT = 47;
  public static final int MINUS = 31;
  public static final int RPAREN = 23;
  public static final int SEMICOLON = 37;
  public static final int AND = 27;
  public static final int RECORD = 21;
  public static final int OR = 50;
  public static final int COMMA = 18;
  public static final int CLASS = 19;
  public static final int DIV = 33;
  public static final int PLUS = 30;
  public static final int IF = 36;
  public static final int ASSIGN = 10;
  public static final int THIS = 15;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int EQUAL = 11;
  public static final int SUPER = 16;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 32;
  public static final int NUMBER = 2;
  public static final int MOD = 34;
  public static final int DEGREE = 52;
  public static final int BREAK = 40;
  public static final int IDENT = 4;
  public static final int VOID = 24;
  public static final int RBRACECURLY = 8;
  public static final int GREATEREQUAL = 14;
  public static final int COLON = 35;
  public static final int ELSE = 51;
  public static final int LBRACE = 44;
  public static final int READ = 43;
  public static final int ENUM = 17;
  public static final int GOTO = 26;
  public static final int WHILE = 39;
  public static final int CHARCONST = 5;
  public static final int RBRACE = 45;
  public static final int BOOLCONST = 3;
  public static final int EXTENDS = 20;
  public static final int PROG = 6;
  public static final int THREEDOTS = 53;
  public static final int DO = 38;
  public static final int PRINT = 25;
}

