
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 20 11:07:40 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACECURLY = 5;
  public static final int INCREMENT = 43;
  public static final int CONST = 7;
  public static final int LOWER = 45;
  public static final int NOTEQUAL = 12;
  public static final int CONTINUE = 38;
  public static final int LPAREN = 19;
  public static final int GREATER = 13;
  public static final int LOWEREQUAL = 46;
  public static final int DECREMENT = 44;
  public static final int MINUS = 28;
  public static final int RPAREN = 20;
  public static final int SEMICOLON = 34;
  public static final int AND = 24;
  public static final int RECORD = 18;
  public static final int OR = 47;
  public static final int COMMA = 15;
  public static final int CLASS = 16;
  public static final int DIV = 30;
  public static final int PLUS = 27;
  public static final int ASSIGN = 8;
  public static final int IF = 33;
  public static final int DOT = 26;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int EQUAL = 11;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int NUMBER = 2;
  public static final int MOD = 31;
  public static final int BREAK = 37;
  public static final int IDENT = 3;
  public static final int VOID = 21;
  public static final int RBRACECURLY = 6;
  public static final int GREATEREQUAL = 14;
  public static final int COLON = 32;
  public static final int ELSE = 48;
  public static final int LBRACE = 41;
  public static final int READ = 40;
  public static final int GOTO = 23;
  public static final int WHILE = 36;
  public static final int CHARCONST = 9;
  public static final int RBRACE = 42;
  public static final int BOOLCONST = 10;
  public static final int EXTENDS = 17;
  public static final int PROG = 4;
  public static final int DO = 35;
  public static final int PRINT = 22;
}

